# -*- coding: utf-8 -*-
"""Count number of occurrences of a word in a plaintext file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKPyAWG9y1XRiZrNNMI4WnropCOAAAmF
"""

# Open the file in read mode
text = open("data.txt", "r")

# Create an empty dictionary
d = dict()

# Loop through each line of the file
for line in text:
	# Remove the leading spaces and newline character
	line = line.strip()

	# Convert the characters in line to
	# lowercase to avoid case mismatch
	line = line.lower()

	# Split the line into words
	words = line.split(" ")
						

	# Iterate over each word in line
	for word in words:
		# Check if the word is already in dictionary
		if word in d:
			# Increment count of word by 1
			d[word] = d[word] + 1
		else:
			# Add the word to dictionary with count 1
			d[word] = 1

#Printing
sorted_d = sorted( ((v,k) for k,v in d.items()), reverse=True)
for i in sorted_d: 
  print(i)

''' Source: 
https://www.geeksforgeeks.org/python-count-occurrences-of-each-word-in-given-text-file/
https://stackoverflow.com/questions/11228812/print-a-dict-sorted-by-values
'''
